# Generated by Django 3.1.7 on 2021-04-19 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210419_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=datetime.datetime(2021, 4, 19, 18, 39, 42, 578787, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
